### ISSUE TITLE
Export has been rolled back 

### ISSUE THREAD

**Issue by wertop** [archi-contribs/database-plugin#108]
While trying to export the model to the MS-SQL database I'm getting the error.
What is the limitation of data length?
How can I identify data I have to change to be able to export the model?

2020-10-13 11:28:42 ERROR 2363:DBGuiExportModel                         └ The transaction has been rolled back to leave the database in a coherent state. You may solve the issue and export again your components.
com.microsoft.sqlserver.jdbc.SQLServerException: String or binary data would be truncated.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:600)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:522)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7225)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3053)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:471)
	at org.archicontribs.database.connection.DBStatement.executeUpdate(DBStatement.java:78)
	at org.archicontribs.database.connection.DBRequest.<init>(DBRequest.java:23)
	at org.archicontribs.database.connection.DBDatabaseConnection.insert(DBDatabaseConnection.java:1233)
	at org.archicontribs.database.connection.DBDatabaseExportConnection.exportElement(DBDatabaseExportConnection.java:1374)
	at org.archicontribs.database.connection.DBDatabaseExportConnection.exportEObject(DBDatabaseExportConnection.java:1319)
	at org.archicontribs.database.GUI.DBGuiExportModel.doExport(DBGuiExportModel.java:2411)
	at org.archicontribs.database.GUI.DBGuiExportModel.export(DBGuiExportModel.java:2228)
	at org.archicontribs.database.GUI.DBGuiExportModel$1.widgetSelected(DBGuiExportModel.java:128)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4173)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3986)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3585)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:633)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at com.archimatetool.editor.Application.start(Application.java:84)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)

**Comment by herve91** [comment]
Hi,

Databases have got constraints about data length and you may have read one of them. Or, as my plugin has been written few years ago, I've put columns length constraints that were necessary with older databases but that could be increased with current databases versions.

To investigate, you need to configure the logger in trace mode and enable the inclusion of SQL requests in the log file. Then you'll have complete details about the component that couldn't be exported to the database and the corresponding SQL request.

You may provide me with the few lines before the exception (with the component and the SQL request) that I investigate, but please do not log the complete log file here as it will contain enough information to reconstruct your model and it may be confidential.

Best regards
Hervé
