### ISSUE TITLE
Importing any component from a Microsoft SQL Server database fails on a non-existing column

### ISSUE THREAD

**Issue by Wowbagger15** [archi-contribs/database-plugin#113]
Hello Hervé,

First off: Thnx for an amazingly useful plugin! Ran into an issue, however.

Using version 2.2.15 of the plugin in Archi 4.8.1 (on Windows) an import from a (Docker containerized) Microsoft SQL Server 2019 database fails on a non-existing column 'RANK':

![image](https://user-images.githubusercontent.com/41243388/107277155-53c2bb00-6a54-11eb-96ed-05ce85c1c8b4.png)

The versioning comments indicate that in a certain previous version some table columns named 'rank' have been renamed to 'pos'. However, the class file

`org/archicontribs/database/connection/DBDatabaseImportConnection.java
`

still seems to reference it:

```
Search "rank" (3 hits in 1 file of 1 searched)
  org/archicontribs/database/connection/DBDatabaseImportConnection.java (3 hits)
	Line 200: 					try ( DBSelect resultProperties = new DBSelect(this.databaseEntry.getName(), this.connection, "SELECT name, value FROM "+this.schemaPrefix+"properties WHERE parent_id = ? AND parent_version = ? ORDER BY RANK", id, version) ) {
	Line 210: 					try ( DBSelect resultFeatures = new DBSelect(this.databaseEntry.getName(), this.connection, "SELECT name, value FROM "+this.schemaPrefix+"features WHERE parent_id = ? AND parent_version = ? ORDER BY RANK", id, version) ) {
	Line 221: 						try ( DBSelect resultBendpoints = new DBSelect(this.databaseEntry.getName(), this.connection, "SELECT start_x, start_y, end_x, end_y FROM "+this.schemaPrefix+"bendpoints WHERE parent_id = ? AND parent_version = ? ORDER BY RANK", id, version ) ) {

```

The tracelog shows this as well:

```
2021-02-08 21:21:24 INFO  2291:DBGuiImportComponents                    - (1/1) Importing elements from model "ArchiMate model".
2021-02-08 21:21:24 ERROR  245:DBGuiImportComponents$5                  - An exception has been raised during import.
com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'RANK'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:600)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:522)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7225)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3053)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:444)
	at org.archicontribs.database.connection.DBStatement.executeQuery(DBStatement.java:55)
	at org.archicontribs.database.connection.DBSelect.<init>(DBSelect.java:29)
	at org.archicontribs.database.connection.DBDatabaseImportConnection.getObjectFromDatabase(DBDatabaseImportConnection.java:200)
	at org.archicontribs.database.model.commands.DBImportElementFromIdCommand.<init>(DBImportElementFromIdCommand.java:102)
	at org.archicontribs.database.GUI.DBGuiImportComponents.doImport(DBGuiImportComponents.java:2300)
	at org.archicontribs.database.GUI.DBGuiImportComponents$5.widgetSelected(DBGuiImportComponents.java:243)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at com.archimatetool.editor.Application.start(Application.java:77)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)

```

Fix *appears* easy enough but Java is not my bread and butter I fear. Is my assumption on par?

Kind regards & keep it up,

Bob

**Comment by herve91** [comment]
Hi Bob,

Thanks for pointing me to this issue. I'll send an update ASAP.

Best regards
Hervé

**Comment by herve91** [comment]
Version 2.2.16 fixes this issue.
