### ISSUE TITLE
Error creating preferences UI, plugin v 2.0.7, archimate 4.0.2

### ISSUE THREAD

**Issue by MarcF88** [archi-contribs/database-plugin#19]
Hi,
The initial loading and configuration of the database plugin works fine, I can configure a database and import, export project. If I then close Archimate, open it again, clicking File -> import -> import from database does nothing, and Edit -> Preferences -> database plugin opens a dialog box with caption 'Could not Accept Changes' and text 'The currently displayed page contains invalid values'. I am getting this behaviour with sqlite and postgres databases.

The file org.archicontribs.database.prefs contains
---------------
checkForUpdateAtStartup=true
closeIfSuccessful=true
databases=1
databases_database_0=archimodels
databases_driver_0=postgresql
databases_export-views-images_0=true
databases_export-whole-model_0=true
databases_name_0=collab
databases_password_0=XXXXXXX
databases_port_0=5432
databases_schema_0=public
databases_server_0=localhost
databases_username_0=marc
eclipse.preferences.version=1
importShared=true
loggerExpert=log4j.rootLogger                               \= DEBUG, stdout, file\r\n\r\nlog4j.appender.stdout                          \= org.apache.log4j.ConsoleAppender\r\nlog4j.appender.stdout.Target                   \= System.out\r\nlog4j.appender.stdout.layout                   \= org.apache.log4j.PatternLayout\r\nlog4j.appender.stdout.layout.ConversionPattern \= %d{yyyy-MM-dd HH\:mm\:ss} %-5p %4L\:%-30.30C{1} %m%n\r\n\r\nlog4j.appender.file                            \= org.apache.log4j.FileAppender\r\nlog4j.appender.file.ImmediateFlush             \= true\r\nlog4j.appender.file.Append                     \= false\r\nlog4j.appender.file.Encoding                   \= UTF-8\r\nlog4j.appender.file.File                       \= C\:\\\\Users\\\\marc\\\\DatabasePlugin.log\r\nlog4j.appender.file.layout                     \= org.apache.log4j.PatternLayout\r\nlog4j.appender.file.layout.ConversionPattern   \= %d{yyyy-MM-dd HH\:mm\:ss} %-5p %4L\:%-30.30C{1} %m%n
loggerLevel=fatal
loggerMode=expert
removeDirtyFlag=true
---------------
DatabasePlugin.log contains
----------------------
2017-08-09 14:59:23 INFO   280:DBPlugin                       - Logger initialised.
2017-08-09 14:59:23 INFO   281:DBPlugin                       - Initialising DatabasePlugin plugin ...
2017-08-09 14:59:23 DEBUG  290:DBPlugin                       - plugin's package  = org.archicontribs.database
2017-08-09 14:59:23 DEBUG  291:DBPlugin                       - plugin's folder   = C:\Users\marc\Development\Archi4\plugins
2017-08-09 14:59:23 DEBUG  292:DBPlugin                       - plugin's filename = C:\Users\marc\Development\Archi4\plugins\org.archicontribs.database_v2.0.7b.jar
2017-08-09 14:59:23 DEBUG  364:DBPlugin$1                     - Checking for a new plugin version on GitHub
2017-08-09 14:59:23 DEBUG  411:DBPlugin$1                     - connecting to https://api.github.com/repos/archi-contribs/database-plugin/contents/v2
2017-08-09 14:59:23 DEBUG  414:DBPlugin$1                     - getting file list
2017-08-09 14:59:23 DEBUG  119:DBArchimateFactory             - initializing DBArchimateFactory
2017-08-09 14:59:24 DEBUG  426:DBPlugin$1                     - searching for plugins jar files
2017-08-09 14:59:24 DEBUG  435:DBPlugin$1                     - found version 2.0.7b (https://raw.githubusercontent.com/archi-contribs/database-plugin/master/v2/org.archicontribs.database_v2.0.7b.jar)
2017-08-09 15:00:02 DEBUG   42:DBCanvasFactory                - initializing DBCanvasFactory
2017-08-09 15:00:12 DEBUG   79:DBPreferencePage               - Setting preference store
2017-08-09 15:00:12 DEBUG   90:DBPreferencePage               - Creating field editors on preference page
2017-08-09 15:03:27 DEBUG   79:DBPreferencePage               - Setting preference store
2017-08-09 15:03:27 DEBUG   90:DBPreferencePage               - Creating field editors on preference page
2017-08-09 15:14:07 INFO    36:DBImporter                     - Importing model.
--------------
Stack traces in Archmate's .log give, for opening the preferences page:

!ENTRY org.eclipse.jface 4 2 2017-08-09 15:03:27.316
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.NoClassDefFoundError: Could not initialize class org.archicontribs.database.GUI.DBGui
	at org.archicontribs.database.preferences.DBPreferencePage.createFieldEditors(DBPreferencePage.java:94)
	at org.eclipse.jface.preference.FieldEditorPreferencePage.createContents(FieldEditorPreferencePage.java:225)
	at org.eclipse.jface.preference.PreferencePage.createControl(PreferencePage.java:241)
	at org.eclipse.jface.preference.PreferenceDialog.createPageControl(PreferenceDialog.java:1430)
	at org.eclipse.jface.preference.PreferenceDialog$9.run(PreferenceDialog.java:1197)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
(and so on)

and when importing a model:
--------------
!ENTRY org.eclipse.ui 4 0 2017-08-09 15:14:07.107
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NoClassDefFoundError: org.archicontribs.database.GUI.DBGui
	at org.archicontribs.database.DBImporter.doImport(DBImporter.java:40)
	at org.archicontribs.database.DBImporter.doImport(DBImporter.java:29)
	at com.archimatetool.editor.actions.ImportModelAction.run(ImportModelAction.java:40)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
--------------------

**Comment by herve91** [comment]
Hi Marc,

That is strange, because the plugin is loaded while it states that it cannot load one plugin's class.

Could you please give me te plugin version you use ? I remember another user experienced issues and it came from a corrupted JAR file. Just in case, could you please try to download the JAR file again from GitHub ?

Best regards
Hervé

**Comment by MarcF88** [comment]
Hi Hervé,
This was version 2.0.7b.jar fresh from the Git repo, on Archi 4.0.2. A colleague just did the same on her machine, from her own independent download, and got exactly the same issue.

I did understand the install instructions correctly, to place the .jar file in the plugins directory, and restart Archi?

Kind regards,
Marc

**Comment by herve91** [comment]
Yes that is correct.

What you may do is to run "Archi -consolelog" from a command line. This will open a console window at the same time than Archi. could you please check that there isn't any other error message in this console ?

Best regards
Hervé

**Comment by MarcF88** [comment]
Ah, well, it gets curiouser and curiouser.
Another colleague installed the plugin, and it worked for him (same versions, his own machine, his own download). He placed his laptop near mine. Now it works for me as well - I have not installed or changed anything I swear. I cannot get it to fail anymore.

I do have another error for you though, something that occurred in my tests yesterday, I *think* when importing a model:

!ENTRY org.eclipse.jface 4 0 2017-08-09 15:14:01.662
!MESSAGE java.lang.NullPointerException
!STACK 0
java.lang.NullPointerException
	at org.archicontribs.database.preferences.DBPreferencePage.performOk(DBPreferencePage.java:411)
	at org.eclipse.jface.preference.PreferenceDialog$8.run(PreferenceDialog.java:905)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.preference.PreferenceDialog.okPressed(PreferenceDialog.java:889)
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.okPressed(FilteredPreferenceDialog.java:409)
	at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.okPressed(WorkbenchPreferenceDialog.java:168)
	at org.eclipse.jface.preference.PreferenceDialog.buttonPressed(PreferenceDialog.java:230)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:618)
(etc)

Maybe this helps?

thx -
Marc

**Comment by herve91** [comment]
A nullPointerException is always a coding issue. So yes, I need to review my code near line 411 of org.archicontribs.database.preferences.DBPreferencePage.performOk. Thanks for the information.

And happy to hear that it works, even if I cannot explain what happened.

I close this issue as it now works. Please feel free to open another one if you discover other issues.

Best regards
Hervé
