### ISSUE TITLE
database-plugin not showing up in 4.0.3

### ISSUE THREAD

**Issue by eddiekopp** [archi-contribs/database-plugin#25]
I have tried to install this plugin with version 4.0.2 and 4.0.3 but the options doesn't show up in the menu. I have followed the installation instructions. Could there be some compatibility issues?

**Comment by herve91** [comment]
Hi Eddie,

Could you please add the "-consolelog" option to Archi and provide me with the error message that is displayed in the console window ?
     - on Windows : archi.exe -consolelog
     - on Linux : archi -consolelog

Best regards
Hervé

**Comment by eddiekopp** [comment]
!SESSION 2017-11-08 13:25:15.586 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=no_NO
Command-line arguments:  -os win32 -ws win32 -arch x86 -clean -consolelog

!ENTRY org.eclipse.update.configurator 4 0 2017-11-08 13:25:17.057
!MESSAGE Unable to access file "plugins/org.archicontribs.database_v2.0.7b.jar!META-INF/MANIFEST.MF".

!ENTRY org.archicontribs.modelrepository 4 0 2017-11-08 13:25:17.998
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.archicontribs.modelrepository [41]
  Unresolved requirement: Require-Bundle: com.archimatetool.editor; bundle-version="4.0.3"

        at org.eclipse.osgi.container.Module.start(Module.java:444)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1599)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.archicontribs.modelrepository 4 0 2017-11-08 13:25:18.642
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.archicontribs.modelrepository [41]
  Unresolved requirement: Require-Bundle: com.archimatetool.editor; bundle-version="4.0.3"

        at org.eclipse.osgi.container.Module.start(Module.java:444)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1536)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

**Comment by eddiekopp** [comment]
C:\Program Files (x86)\Archi4\plugins>dir org.archicontribs.*
 Volume in drive C is OSDisk
 Volume Serial Number is 36AF-19BA

 Directory of C:\Program Files (x86)\Archi4\plugins

24.10.2017  09:50            44 659 org.archicontribs.database_v2.0.7b.jar
08.11.2017  11:48         2 796 004 org.archicontribs.modelrepository_0.2.8.201709191142.jar
               2 File(s)      2 840 663 bytes
               0 Dir(s)  185 168 642 048 bytes free

**Comment by herve91** [comment]
Thanks.

The org.archicontribs.database_v2.0.7b.jar file has not got the right size. Should be 16 503 049 bytes.

I believe that you had an issue downloading it. Could you please download it again ?

the method I use at work : click on the jar file, then on the new page, click on the "download" button on the right hand side.

Best regards
Hervé

**Comment by eddiekopp** [comment]
Thanks, 

The options shows up in the export and import menu now. I haven't tried exporting yet but I guess it works :)

Thanks for your kind help and contributions :)
