### ISSUE TITLE
Preferences for Database Plugin not working in Archi 4.2.0

### ISSUE THREAD

**Issue by steve-d-mottram** [archi-contribs/database-plugin#34]
Hi, I have installed version 2.0.7 of the plugin on Archi 4.2.0. When I select the Edit>Preferences menu item, and then in the Preferences window, select the "database plugin" option to configure the plugin, an error dialog box appears saying "Could not accept changes: The currently displayed page contains invalid values". The dialog appears immediately, while the previously selected configuration pane is still displayed.  If I click Ok in the error dialog, the plugin's configuration tab appears, but with no controls displayed. I have attached screenshots below.

![error dialog](https://user-images.githubusercontent.com/8301525/38880180-fd5b703a-425c-11e8-8898-8505b4c07853.png)
![preferences](https://user-images.githubusercontent.com/8301525/38880182-fd76e4d2-425c-11e8-9e60-236565d89cff.png)

**Comment by GeoffMurray** [comment]
Does this thread help you at all? https://github.com/archi-contribs/database-plugin/issues/28

**Comment by steve-d-mottram** [comment]
Hi, thanks for looking into this. The console output is:

Exception in thread "checkForUpdate" java.lang.ExceptionInInitializerError
        at org.archicontribs.database.DBPlugin$1.run(DBPlugin.java:483)
Caused by: java.lang.NullPointerException
        at org.archicontribs.database.GUI.DBGui.<clinit>(DBGui.java:128)
        ... 1 more
!SESSION 2018-04-20 15:41:49.633 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_144
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -clean -consolelog

!ENTRY org.eclipse.jface 4 2 2018-04-20 15:42:23.605
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.NoClassDefFoundError: Could not initialize class org.archicontribs.database.GUI.DBGui
        at org.archicontribs.database.preferences.DBPreferencePage.createFieldEditors(DBPreferencePage.java:94)
        at org.eclipse.jface.preference.FieldEditorPreferencePage.createContents(FieldEditorPreferencePage.java:225)
        at org.eclipse.jface.preference.PreferencePage.createControl(PreferencePage.java:241)
        at org.eclipse.jface.preference.PreferenceDialog.createPageControl(PreferenceDialog.java:1426)
        at org.eclipse.jface.preference.PreferenceDialog$8.run(PreferenceDialog.java:1193)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
        at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
        at org.eclipse.jface.preference.PreferenceDialog.showPage(PreferenceDialog.java:1185)
        at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.showPage(FilteredPreferenceDialog.java:591)
        at org.eclipse.jface.preference.PreferenceDialog$5.lambda$0(PreferenceDialog.java:657)
        at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
        at org.eclipse.jface.preference.PreferenceDialog$5.selectionChanged(PreferenceDialog.java:654)
        at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:872)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
        at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
        at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:869)
        at org.eclipse.jface.viewers.StructuredViewer.handlePostSelect(StructuredViewer.java:1238)
        at org.eclipse.jface.viewers.StructuredViewer.lambda$0(StructuredViewer.java:1261)
        at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:81)
        at org.eclipse.jface.util.OpenStrategy.firePostSelectionEvent(OpenStrategy.java:261)
        at org.eclipse.jface.util.OpenStrategy.access$5(OpenStrategy.java:256)
        at org.eclipse.jface.util.OpenStrategy$1.lambda$1(OpenStrategy.java:426)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4213)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3820)
        at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
        at org.eclipse.jface.window.Window.open(Window.java:794)
        at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.open(WorkbenchPreferenceDialog.java:211)
        at org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:63)
        at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
        at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
        at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
        at com.archimatetool.editor.Application.start(Application.java:81)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1499)

**Comment by herve91** [comment]
Hi Steve,

You closed the issue. Does that mean that you solved it ?

Best regards
Hervé
