### ISSUE TITLE
can't export model including components imported in shared mode

### ISSUE THREAD

**Issue by odulek** [archi-contribs/database-plugin#47]
Hi,
I create a model and import in shared mode a component from another model.
Then I add some components in the new model and want to export it (tried with PostGreSQL and sqlite)

--> export fails, because the plugin tries to insert the component I share with another model.

Is it an issue or maybe I did not understand how the shared mode works ?

Thanks in advance for your help

**Comment by herve91** [comment]
Hi,

The shared mode allow to share components across models. So exporting a model in which you've got a shared component should definitively work.

Could you please switch the plugin's log level to "trace" and send me the last lines of the log file (I need at least the latest SQL request, the error message and the exception stack trace).

Best regards
Hervé

**Comment by odulek** [comment]
Hi,
thank you for this great database plugin.

Please find the lines below.
Thank you for your help.

Kind regards
Olivier

-------------------------------------
2018-10-22 12:06:49 INFO    32:DBExporter                               - Exporting model IE_Import
2018-10-22 12:06:49 DEBUG  231:DBGui                                    - Creating Form GUI.
2018-10-22 12:06:49 DEBUG  111:DBGuiExportModel                         - Setting up GUI for exporting model "IE_Import" (plugin version 2.1.2).
2018-10-22 12:06:49 DEBUG  205:DBArchimateModel                         - Reseting model's counters.
2018-10-22 12:06:49 DEBUG  256:DBArchimateModel                         - Counting objects in selected model.
2018-10-22 12:06:49 DEBUG  156:DBGuiExportModel                         - The model has got 2 elements and 0 relationships and 9 folders and 1 views and 2 objects and 0 connections.
2018-10-22 12:06:49 DEBUG  203:DBDatabaseEntry                          - Getting databases preferences from preference store
2018-10-22 12:06:49 INFO  1179:DBGui                                    - Connecting to the database ...
2018-10-22 12:06:49 DEBUG  623:DBGui                                    - Selected database = archi43_1 (postgresql, localhost, 5432, archi4, archi4, archi4)
2018-10-22 12:06:49 DEBUG  101:DBDatabaseConnection                     - Opening connection to database archi43_1: driver=postgresql, server=localhost, port=5432, database=archi4, schema=archi43, username=archi4
2018-10-22 12:06:49 DEBUG  137:DBDatabaseConnection                     - JDBC class = org.postgresql.Driver
2018-10-22 12:06:49 DEBUG  140:DBDatabaseConnection                     - JDBC connection string = jdbc:postgresql://localhost:5432/archi4
2018-10-22 12:06:49 DEBUG  146:DBDatabaseConnection                     - Connecting with username = archi4
2018-10-22 12:06:49 DEBUG  166:DBDatabaseConnection                     - Will use schema archi43.
2018-10-22 12:06:49 DEBUG  629:DBGui                                    - We are connected to the database.
2018-10-22 12:06:49 INFO  1179:DBGui                                    - Checking the database structure...
2018-10-22 12:06:49 TRACE  310:DBDatabaseConnection                     - Checking "archi43.database_version" table
2018-10-22 12:06:49 TRACE 1278:DBDatabaseConnection                     -       --> SELECT version FROM archi43.database_version WHERE archi_plugin = 'DatabasePlugin'
2018-10-22 12:06:49 TRACE 1278:DBDatabaseConnection                     -       --> SELECT version, created_by, created_on, name, note, purpose FROM archi43.models WHERE id = 'f98c8342-d216-4da2-bad2-1db3a17066d5' ORDER BY version DESC
2018-10-22 12:06:49 INFO  1179:DBGui                                    - Comparing model from the database...
2018-10-22 12:06:49 DEBUG  117:DBDatabaseExportConnection               - Getting versions of the model from the database
2018-10-22 12:06:49 TRACE 1278:DBDatabaseConnection                     -       --> SELECT version, checksum, created_on FROM archi43.models WHERE id = 'f98c8342-d216-4da2-bad2-1db3a17066d5' AND version = (SELECT MAX(version) FROM archi43.models WHERE id = 'f98c8342-d216-4da2-bad2-1db3a17066d5')
2018-10-22 12:06:49 DEBUG  141:DBDatabaseExportConnection               - The model does not exist in the database
2018-10-22 12:06:49 DEBUG  147:DBDatabaseExportConnection               -    Initial version = 0
2018-10-22 12:06:49 DEBUG  148:DBDatabaseExportConnection               -    Current version = 0
2018-10-22 12:06:49 DEBUG  149:DBDatabaseExportConnection               -    Database version = 0
2018-10-22 12:06:49 DEBUG  289:DBDatabaseExportConnection               - Getting versions of the elements from the database
2018-10-22 12:06:49 TRACE 1278:DBDatabaseConnection                     -       --> SELECT id, name, version, checksum, created_on, model_id, model_version FROM archi43.elements LEFT JOIN archi43.elements_in_model ON element_id = id AND element_version = version WHERE id IN (SELECT id FROM archi43.elements JOIN archi43.elements_in_model ON element_id = id AND element_version = version WHERE model_id = 'f98c8342-d216-4da2-bad2-1db3a17066d5' AND model_version = 0) ORDER BY id, version, model_version
2018-10-22 12:06:49 DEBUG  348:DBDatabaseExportConnection               - Getting versions of the relationships from the database
2018-10-22 12:06:49 TRACE 1278:DBDatabaseConnection                     -       --> SELECT id, name, version, checksum, created_on, model_id, model_version FROM archi43.relationships LEFT JOIN archi43.relationships_in_model ON relationship_id = id AND relationship_version = version WHERE id IN (SELECT id FROM archi43.relationships JOIN archi43.relationships_in_model ON relationship_id = id AND relationship_version = version WHERE model_id = 'f98c8342-d216-4da2-bad2-1db3a17066d5' AND model_version = 0) ORDER BY id, version, model_version
2018-10-22 12:06:49 DEBUG  407:DBDatabaseExportConnection               - Getting versions of the folders from the database
2018-10-22 12:06:49 TRACE 1278:DBDatabaseConnection                     -       --> SELECT id, name, version, checksum, created_on, model_id, model_version FROM archi43.folders LEFT JOIN archi43.folders_in_model ON folder_id = id AND folder_version = version WHERE id IN (SELECT id FROM archi43.folders JOIN archi43.folders_in_model ON folder_id = id AND folder_version = version WHERE model_id = 'f98c8342-d216-4da2-bad2-1db3a17066d5' AND model_version = 0) ORDER BY id, version, model_version
2018-10-22 12:06:49 DEBUG  465:DBDatabaseExportConnection               - Getting versions of the views from the database
2018-10-22 12:06:49 TRACE 1278:DBDatabaseConnection                     -       --> SELECT id, name, version, checksum, container_checksum, created_on, model_id, model_version FROM archi43.views LEFT JOIN archi43.views_in_model ON view_id = id AND view_version = version WHERE id IN (SELECT id FROM archi43.views JOIN archi43.views_in_model ON view_id = id AND view_version = version WHERE model_id = 'f98c8342-d216-4da2-bad2-1db3a17066d5' AND model_version = 0) ORDER BY id, version, model_version
2018-10-22 12:06:49 DEBUG  525:DBDatabaseExportConnection               - Checking missing images from the database
2018-10-22 12:06:49 TRACE 1278:DBDatabaseConnection                     -       --> SELECT DISTINCT image_path FROM archi43.views_objects JOIN archi43.views_objects_in_view ON views_objects_in_view.object_id = views_objects.id AND views_objects_in_view.object_version = views_objects.version JOIN archi43.views_in_model ON views_in_model.view_id = views_objects_in_view.view_id AND views_in_model.view_version = views_objects_in_view.view_version WHERE image_path IS NOT NULL AND views_in_model.model_id = 'f98c8342-d216-4da2-bad2-1db3a17066d5' AND views_in_model.model_version = 0
2018-10-22 12:06:49 DEBUG  545:DBDatabaseExportConnection               - Checking if the images exist in the database
2018-10-22 12:06:49 INFO  1179:DBGui                                    - Calculating number of new, updated and deleted components.
2018-10-22 12:06:49 TRACE 1278:DBDatabaseConnection                     -       --> SELECT id, name, version, checksum, created_on, model_id, model_version FROM archi43.elements LEFT JOIN archi43.elements_in_model ON element_id = id AND element_version = version WHERE id = '6a63776a-3956-4310-8970-9abcf97de0f7' ORDER BY version, model_version
2018-10-22 12:06:49 TRACE 1278:DBDatabaseConnection                     -       --> SELECT id, name, version, checksum, created_on, model_id, model_version FROM archi43.elements LEFT JOIN archi43.elements_in_model ON element_id = id AND element_version = version WHERE id = '6afa8e2c-d38d-4956-ab17-769e41c90fff' ORDER BY version, model_version
2018-10-22 12:06:49 TRACE 1278:DBDatabaseConnection                     -       --> SELECT id, name, version, checksum, created_on, model_id, model_version FROM archi43.folders LEFT JOIN archi43.folders_in_model ON folder_id = id AND folder_version = version WHERE id = 'c1050c38-7bd1-4c1e-9084-c3b15ceab837' ORDER BY version, model_version
2018-10-22 12:06:49 TRACE 1278:DBDatabaseConnection                     -       --> SELECT id, name, version, checksum, created_on, model_id, model_version FROM archi43.folders LEFT JOIN archi43.folders_in_model ON folder_id = id AND folder_version = version WHERE id = 'c607b111-ca7f-40fd-a7bf-da9c9b5d0f95' ORDER BY version, model_version
2018-10-22 12:06:49 TRACE 1278:DBDatabaseConnection                     -       --> SELECT id, name, version, checksum, created_on, model_id, model_version FROM archi43.folders LEFT JOIN archi43.folders_in_model ON folder_id = id AND folder_version = version WHERE id = '1e8106ec-f40b-4cd4-bc1c-de2d71253ee9' ORDER BY version, model_version
2018-10-22 12:06:49 TRACE 1278:DBDatabaseConnection                     -       --> SELECT id, name, version, checksum, created_on, model_id, model_version FROM archi43.folders LEFT JOIN archi43.folders_in_model ON folder_id = id AND folder_version = version WHERE id = 'c50d6430-df78-4c10-979f-d11b9634c8e5' ORDER BY version, model_version
2018-10-22 12:06:49 TRACE 1278:DBDatabaseConnection                     -       --> SELECT id, name, version, checksum, created_on, model_id, model_version FROM archi43.folders LEFT JOIN archi43.folders_in_model ON folder_id = id AND folder_version = version WHERE id = '1609b927-cb18-4183-a15c-f71c9d1099e1' ORDER BY version, model_version
2018-10-22 12:06:49 TRACE 1278:DBDatabaseConnection                     -       --> SELECT id, name, version, checksum, created_on, model_id, model_version FROM archi43.folders LEFT JOIN archi43.folders_in_model ON folder_id = id AND folder_version = version WHERE id = '9832451b-608c-4d9a-bdf7-9ef4379319fb' ORDER BY version, model_version
2018-10-22 12:06:49 TRACE 1278:DBDatabaseConnection                     -       --> SELECT id, name, version, checksum, created_on, model_id, model_version FROM archi43.folders LEFT JOIN archi43.folders_in_model ON folder_id = id AND folder_version = version WHERE id = '4bcefdb8-2743-4d18-91cd-51698185c1f8' ORDER BY version, model_version
2018-10-22 12:06:49 TRACE 1278:DBDatabaseConnection                     -       --> SELECT id, name, version, checksum, created_on, model_id, model_version FROM archi43.folders LEFT JOIN archi43.folders_in_model ON folder_id = id AND folder_version = version WHERE id = '88748dd0-9177-47cd-a5cd-a7787db33916' ORDER BY version, model_version
2018-10-22 12:06:49 TRACE 1278:DBDatabaseConnection                     -       --> SELECT id, name, version, checksum, created_on, model_id, model_version FROM archi43.folders LEFT JOIN archi43.folders_in_model ON folder_id = id AND folder_version = version WHERE id = 'e0039434-96b8-4e6b-9e5f-0835ac88c367' ORDER BY version, model_version
2018-10-22 12:06:49 TRACE 1278:DBDatabaseConnection                     -       --> SELECT id, name, version, checksum, container_checksum, created_on, model_id, model_version FROM archi43.views LEFT JOIN archi43.views_in_model ON view_id = id AND view_version = version WHERE id = '5857d1fe-b348-47af-a122-5e58208a02d8' ORDER BY version, model_version
2018-10-22 12:06:49 TRACE 1278:DBDatabaseConnection                     -       --> SELECT id, name, version, checksum, created_on, view_id as model_id, view_version as model_version FROM archi43.views_objects LEFT JOIN archi43.views_objects_in_view ON object_id = id AND object_version = version WHERE id = 'ce1f2ac2-1feb-461d-b709-2c7a03891383' ORDER BY version, view_version
2018-10-22 12:06:49 TRACE 1278:DBDatabaseConnection                     -       --> SELECT id, name, version, checksum, created_on, view_id as model_id, view_version as model_version FROM archi43.views_objects LEFT JOIN archi43.views_objects_in_view ON object_id = id AND object_version = version WHERE id = '9ff342ca-255f-4766-9200-48cbe9c40654' ORDER BY version, view_version
2018-10-22 12:07:03 DEBUG  582:DBGui                                    - Openning preference page ...
2018-10-22 12:07:03 DEBUG   89:DBPreferencePage                         - Setting preference store
2018-10-22 12:07:03 DEBUG  101:DBPreferencePage                         - Creating field editors on preference page
2018-10-22 12:07:03 DEBUG  203:DBDatabaseEntry                          - Getting databases preferences from preference store
2018-10-22 12:07:06 DEBUG  602:DBGui                                    - Preferences cancelled ...
2018-10-22 12:07:08 INFO  1609:DBGuiExportModel                         - Exporting model: 
2018-10-22 12:07:08 INFO  1610:DBGuiExportModel                         -                             <------ In model ------>   <----- In database ---->
2018-10-22 12:07:08 INFO  1611:DBGuiExportModel                         -                     Total      New  Updated  Deleted      New  Updated  Deleted Conflict
2018-10-22 12:07:08 INFO  1612:DBGuiExportModel                         -    Elements:            2        2        0        0        0        0        0        0
2018-10-22 12:07:08 INFO  1613:DBGuiExportModel                         -    Relationships:       0        0        0        0        0        0        0        0
2018-10-22 12:07:08 INFO  1615:DBGuiExportModel                         -    Folders:             9        9        0        0        0        0        0        0
2018-10-22 12:07:08 INFO  1616:DBGuiExportModel                         -    views:               1        1        0        0        0        0        0        0
2018-10-22 12:07:08 INFO  1617:DBGuiExportModel                         -    Objects:             2        2        0        0        0        0        0        0
2018-10-22 12:07:08 INFO  1618:DBGuiExportModel                         -    Connections:         0        0        0        0        0        0        0        0
2018-10-22 12:07:08 INFO  1619:DBGuiExportModel                         -    images:              0        0                          0
2018-10-22 12:07:08 DEBUG 1461:DBDatabaseConnection                     - Setting database auto commit to false
2018-10-22 12:07:08 INFO  1179:DBGui                                    - Comparing model from the database...
2018-10-22 12:07:08 DEBUG  117:DBDatabaseExportConnection               - Getting versions of the model from the database
2018-10-22 12:07:08 TRACE 1278:DBDatabaseConnection                     -       --> SELECT version, checksum, created_on FROM archi43.models WHERE id = 'f98c8342-d216-4da2-bad2-1db3a17066d5' AND version = (SELECT MAX(version) FROM archi43.models WHERE id = 'f98c8342-d216-4da2-bad2-1db3a17066d5')
2018-10-22 12:07:08 DEBUG  141:DBDatabaseExportConnection               - The model does not exist in the database
2018-10-22 12:07:08 DEBUG  147:DBDatabaseExportConnection               -    Initial version = 0
2018-10-22 12:07:08 DEBUG  148:DBDatabaseExportConnection               -    Current version = 0
2018-10-22 12:07:08 DEBUG  149:DBDatabaseExportConnection               -    Database version = 0
2018-10-22 12:07:08 DEBUG  289:DBDatabaseExportConnection               - Getting versions of the elements from the database
2018-10-22 12:07:08 TRACE 1278:DBDatabaseConnection                     -       --> SELECT id, name, version, checksum, created_on, model_id, model_version FROM archi43.elements LEFT JOIN archi43.elements_in_model ON element_id = id AND element_version = version WHERE id IN (SELECT id FROM archi43.elements JOIN archi43.elements_in_model ON element_id = id AND element_version = version WHERE model_id = 'f98c8342-d216-4da2-bad2-1db3a17066d5' AND model_version = 0) ORDER BY id, version, model_version
2018-10-22 12:07:08 DEBUG  348:DBDatabaseExportConnection               - Getting versions of the relationships from the database
2018-10-22 12:07:08 TRACE 1278:DBDatabaseConnection                     -       --> SELECT id, name, version, checksum, created_on, model_id, model_version FROM archi43.relationships LEFT JOIN archi43.relationships_in_model ON relationship_id = id AND relationship_version = version WHERE id IN (SELECT id FROM archi43.relationships JOIN archi43.relationships_in_model ON relationship_id = id AND relationship_version = version WHERE model_id = 'f98c8342-d216-4da2-bad2-1db3a17066d5' AND model_version = 0) ORDER BY id, version, model_version
2018-10-22 12:07:08 DEBUG  407:DBDatabaseExportConnection               - Getting versions of the folders from the database
2018-10-22 12:07:08 TRACE 1278:DBDatabaseConnection                     -       --> SELECT id, name, version, checksum, created_on, model_id, model_version FROM archi43.folders LEFT JOIN archi43.folders_in_model ON folder_id = id AND folder_version = version WHERE id IN (SELECT id FROM archi43.folders JOIN archi43.folders_in_model ON folder_id = id AND folder_version = version WHERE model_id = 'f98c8342-d216-4da2-bad2-1db3a17066d5' AND model_version = 0) ORDER BY id, version, model_version
2018-10-22 12:07:08 DEBUG  465:DBDatabaseExportConnection               - Getting versions of the views from the database
2018-10-22 12:07:08 TRACE 1278:DBDatabaseConnection                     -       --> SELECT id, name, version, checksum, container_checksum, created_on, model_id, model_version FROM archi43.views LEFT JOIN archi43.views_in_model ON view_id = id AND view_version = version WHERE id IN (SELECT id FROM archi43.views JOIN archi43.views_in_model ON view_id = id AND view_version = version WHERE model_id = 'f98c8342-d216-4da2-bad2-1db3a17066d5' AND model_version = 0) ORDER BY id, version, model_version
2018-10-22 12:07:08 DEBUG  525:DBDatabaseExportConnection               - Checking missing images from the database
2018-10-22 12:07:08 TRACE 1278:DBDatabaseConnection                     -       --> SELECT DISTINCT image_path FROM archi43.views_objects JOIN archi43.views_objects_in_view ON views_objects_in_view.object_id = views_objects.id AND views_objects_in_view.object_version = views_objects.version JOIN archi43.views_in_model ON views_in_model.view_id = views_objects_in_view.view_id AND views_in_model.view_version = views_objects_in_view.view_version WHERE image_path IS NOT NULL AND views_in_model.model_id = 'f98c8342-d216-4da2-bad2-1db3a17066d5' AND views_in_model.model_version = 0
2018-10-22 12:07:08 DEBUG  545:DBDatabaseExportConnection               - Checking if the images exist in the database
2018-10-22 12:07:08 DEBUG  715:DBDatabaseExportConnection               - Exporting model (initial version = 0, exported version = 1, latest database version = 0)
2018-10-22 12:07:08 TRACE 1278:DBDatabaseConnection                     -       --> INSERT INTO archi43.models (id, version, name, note, purpose, created_by, created_on, checksum) VALUES ('f98c8342-d216-4da2-bad2-1db3a17066d5', 1, 'IE_Import', '', '', 'PPBF381', 2018-10-22 12:07:08.302, '')
2018-10-22 12:07:08 INFO  1721:DBGuiExportModel                         - There is no folder to import.
2018-10-22 12:07:08 INFO  1747:DBGuiExportModel                         - There is no element to import.
2018-10-22 12:07:08 INFO  1772:DBGuiExportModel                         - There is no relationship to import.
2018-10-22 12:07:08 INFO  1808:DBGuiExportModel                         - There is no view to import.
2018-10-22 12:07:08 INFO  1833:DBGuiExportModel                         - There is no view object to import.
2018-10-22 12:07:08 INFO  1857:DBGuiExportModel                         - There is no view connection to import.
2018-10-22 12:07:08 INFO  1890:DBGuiExportModel                         - Checking if components have been moved to new folder ...
2018-10-22 12:07:08 TRACE 1278:DBDatabaseConnection                     -       --> SELECT m2.element_id AS element_id, m2.parent_folder_id AS parent_folder_id FROM archi43.elements_in_model m1 JOIN archi43.elements_in_model m2 ON m1.element_id = m2.element_id AND m1.model_id = m2.model_id WHERE m1.model_id = 'f98c8342-d216-4da2-bad2-1db3a17066d5' AND m1.model_version = 0 AND m2.model_version = 0 AND m1.parent_folder_id <> m2.parent_folder_id
2018-10-22 12:07:08 TRACE 1278:DBDatabaseConnection                     -       --> SELECT m2.relationship_id AS relationship_id, m2.parent_folder_id AS parent_folder_id FROM archi43.relationships_in_model m1 JOIN archi43.relationships_in_model m2 ON m1.relationship_id = m2.relationship_id AND m1.model_id = m2.model_id WHERE m1.model_id = 'f98c8342-d216-4da2-bad2-1db3a17066d5' AND m1.model_version = 0 AND m2.model_version = 0 AND m1.parent_folder_id <> m2.parent_folder_id
2018-10-22 12:07:08 TRACE 1278:DBDatabaseConnection                     -       --> SELECT m2.folder_id AS folder_id, m2.parent_folder_id AS parent_folder_id FROM archi43.folders_in_model m1 JOIN archi43.folders_in_model m2 ON m1.folder_id = m2.folder_id AND m1.model_id = m2.model_id WHERE m1.model_id = 'f98c8342-d216-4da2-bad2-1db3a17066d5' AND m1.model_version = 0 AND m2.model_version = 0 AND m1.parent_folder_id <> m2.parent_folder_id
2018-10-22 12:07:08 TRACE 1278:DBDatabaseConnection                     -       --> SELECT m2.view_id AS view_id, m2.parent_folder_id AS parent_folder_id FROM archi43.views_in_model m1 JOIN archi43.views_in_model m2 ON m1.view_id = m2.view_id AND m1.model_id = m2.model_id WHERE m1.model_id = 'f98c8342-d216-4da2-bad2-1db3a17066d5' AND m1.model_version = 0 AND m2.model_version = 0 AND m1.parent_folder_id <> m2.parent_folder_id
2018-10-22 12:07:08 INFO  1902:DBGuiExportModel                         - There is no component to move to a new folder.
2018-10-22 12:07:08 INFO  1905:DBGuiExportModel                         - Exporting elements ...
2018-10-22 12:07:08 DEBUG 2142:DBGuiExportModel                         - Do Export BusinessService:"Ouverture Contenant"(6a63776a-3956-4310-8970-9abcf97de0f7)
2018-10-22 12:07:08 DEBUG 2263:DBGuiExportModel                         - The Element has been created in the model, we must export it to the database.
2018-10-22 12:07:08 DEBUG  771:DBDatabaseExportConnection               - Exporting BusinessService:"Ouverture Contenant"(6a63776a-3956-4310-8970-9abcf97de0f7) (initial version = 0, exported version = 1, database_version = 0, latest_database_version = 0)
2018-10-22 12:07:08 TRACE 1278:DBDatabaseConnection                     -       --> INSERT INTO archi43.elements (id, version, class, name, documentation, created_by, created_on, checksum) VALUES ('6a63776a-3956-4310-8970-9abcf97de0f7', 1, 'BusinessService', 'Ouverture Contenant', '', 'PPBF381', 2018-10-22 12:07:08.302, '44e72c68efe6c64612d47887154458d1')
2018-10-22 12:07:08 TRACE 1373:DBDatabaseConnection                     - Rolled back to savepoint
2018-10-22 12:07:08 DEBUG 1477:DBDatabaseConnection                     - Rollbacking database transaction.
2018-10-22 12:07:08 DEBUG 2588:DBGuiExportModel                         - Showing result.
2018-10-22 12:07:08 ERROR 1177:DBGui                                    ┌ Error while exporting model.
2018-10-22 12:07:08 ERROR 1177:DBGui                                    │ ERREUR: la valeur d'une clé dupliquée rompt la contrainte unique « elements_pkey »
2018-10-22 12:07:08 ERROR 1177:DBGui                                    └   Détail : La clé « (id, version)=(6a63776a-3956-4310-8970-9abcf97de0f7, 1) » existe déjà.
2018-10-22 12:07:08 FATAL 2001:DBGuiExportModel                         ┌ An error occurred while exporting the components.
2018-10-22 12:07:08 FATAL 2001:DBGuiExportModel                         │ 
2018-10-22 12:07:08 FATAL 2001:DBGuiExportModel                         └ The transaction has been rolled back to leave the database in a coherent state. You may solve the issue and export again your components.
org.postgresql.util.PSQLException: ERREUR: la valeur d'une clé dupliquée rompt la contrainte unique « elements_pkey »
  Détail : La clé « (id, version)=(6a63776a-3956-4310-8970-9abcf97de0f7, 1) » existe déjà.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2422)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2167)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
	at org.archicontribs.database.connection.DBDatabaseConnection.request(DBDatabaseConnection.java:1368)
	at org.archicontribs.database.connection.DBDatabaseConnection.insert(DBDatabaseConnection.java:1341)
	at org.archicontribs.database.connection.DBDatabaseExportConnection.exportElement(DBDatabaseExportConnection.java:785)
	at org.archicontribs.database.connection.DBDatabaseExportConnection.exportEObject(DBDatabaseExportConnection.java:741)
	at org.archicontribs.database.GUI.DBGuiExportModel.doExportEObject(DBGuiExportModel.java:2265)

**Comment by odulek** [comment]
OK Hervé, thank you, I send you an email.
