### ISSUE TITLE
export to Sqlite on Ubuntu ("arithmetic exception: / by zero")

### ISSUE THREAD

**Issue by steve-vincent** [archi-contribs/database-plugin#52]
just passing it on.
glad to give more info if needed

**Comment by herve91** [comment]
Hi Steve,

Could you please switch the plugin's log level to "trace" and send me the last lines including the complete exception trace and few lines before the exception that I can understand the conditions where the exception is raised.

Thanks and regards
Hervé

**Comment by steve-vincent** [comment]
2018-11-10 02:11:10 INFO    32:DBExporter                               - Exporting model test
2018-11-10 02:11:10 DEBUG  231:DBGui                                    - Creating Form GUI.
2018-11-10 02:11:10 ERROR   38:DBExporter                               - Cannot export model
java.lang.ArithmeticException: / by zero
	at org.archicontribs.database.GUI.DBGui.<init>(DBGui.java:241)
	at org.archicontribs.database.GUI.DBGuiExportModel.<init>(DBGuiExportModel.java:106)
	at org.archicontribs.database.DBExporter.export(DBExporter.java:35)
	at com.archimatetool.editor.actions.ExportModelAction.run(ExportModelAction.java:37)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5348)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4602)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4183)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at com.archimatetool.editor.Application.start(Application.java:81)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)

**Comment by herve91** [comment]
Thanks a lot.

In fact, to center the export/import window, I calculate a scale factor to the in account 4K displays.

Unfortunately, on some environments, the scale factor calculation gives zero, so when I divide the screen width and height by this scale factor, I get a divide by zero exception.

I added a test to default this scale factor to one rather than zero.

I will be fixed in the next release. Thanks for your help.

Best regards
Hervé
