### ISSUE TITLE
v2.1.5 SQLSyntaxErrorException: ORA-2182: savepoint name expected

### ISSUE THREAD

**Issue by kaiserghetto** [archi-contribs/database-plugin#54]
Seems that something is missing with the new version that addresses my previously reported Oracle auto commit issue. I now get this error at the same step. 

 Looking to create new DB for it. Worked fine with MySQL, not with Oracle. Below log in Expert mode including traces.

> 2018-11-12 10:26:25 INFO   354:DBPlugin                                 - Logger initialised.
2018-11-12 10:26:25 INFO   355:DBPlugin                                 - Initialising DatabasePlugin plugin ...
2018-11-12 10:26:25 INFO   357:DBPlugin                                 - ===============================================
2018-11-12 10:26:25 ERROR  404:DBPlugin                                 ┌ The database plugin has been correctly downloaded to "C:\Program Files\Archi4\plugins\org.archicontribs.database_v2.1.5.jar
2018-11-12 10:26:25 ERROR  404:DBPlugin                                 │ " but you are still using the database plugin version 2.1.5.
2018-11-12 10:26:25 ERROR  404:DBPlugin                                 │ 
2018-11-12 10:26:25 ERROR  404:DBPlugin                                 └ Please check the plugin files located in the "C:\Program Files\Archi4\plugins" folder.
2018-11-12 10:26:40 INFO  1188:DBGui                                    - Connecting to the database ...
2018-11-12 10:26:41 INFO  1188:DBGui                                    - Checking the database structure...
2018-11-12 10:26:45 INFO  1188:DBGui                                    - Creating necessary database tables ...
2018-11-12 10:26:45 ERROR  167:DBGuiExportModel                         - Cannot use this database.
java.sql.SQLSyntaxErrorException: ORA-02182: savepoint name expected

>	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1052)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:537)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:255)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:610)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:213)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:37)
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:887)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1136)
	at oracle.jdbc.driver.OracleStatement.executeUpdateInternal(OracleStatement.java:1678)
	at oracle.jdbc.driver.OracleStatement.executeLargeUpdate(OracleStatement.java:1643)
	at oracle.jdbc.driver.OracleStatement.executeUpdate(OracleStatement.java:1630)
	at oracle.jdbc.driver.OracleStatementWrapper.executeUpdate(OracleStatementWrapper.java:282)
	at oracle.jdbc.driver.PhysicalConnection.rollback(PhysicalConnection.java:4060)
	at org.archicontribs.database.connection.DBDatabaseConnection.rollback(DBDatabaseConnection.java:1481)
	at org.archicontribs.database.connection.DBDatabaseConnection.rollback(DBDatabaseConnection.java:1486)
	at org.archicontribs.database.connection.DBDatabaseConnection.checkDatabase(DBDatabaseConnection.java:337)
	at org.archicontribs.database.GUI.DBGui.databaseSelected(DBGui.java:648)
	at org.archicontribs.database.GUI.DBGui$5.widgetSelected(DBGui.java:457)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:802)
	at org.archicontribs.database.GUI.DBGui.getDatabases(DBGui.java:581)
	at org.archicontribs.database.GUI.DBGuiExportModel.run(DBGuiExportModel.java:167)
	at org.archicontribs.database.menu.DBMenuModelExportHandler.execute(DBMenuModelExportHandler.java:47)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:390)
	at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:820)
	at org.eclipse.ui.menus.CommandContributionItem.lambda$3(CommandContributionItem.java:797)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at com.archimatetool.editor.Application.start(Application.java:81)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
>Caused by: Error : 2182, Position : 12, Sql = ROLLBACK TO null, OriginalSql = ROLLBACK TO null, Error Msg = ORA-02182: savepoint name expected

>	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
	... 72 more

**Comment by herve91** [comment]
Thanks for pointing out this issue.

Fixed in release 2.1.6.

Nevertheless, table and trigger creation cannot be rolled back so I believe that you're now in a un-managed situation ... Some tables and triggers may have already been already created, but not all of them.

I recommend you manually delete them or completely re-initialize your database before the plugin can create all them in one go.

Please let me know if you require some assistance for this

Best regards
Hervé

**Comment by herve91** [comment]
That's the issue with Oracle ... Everything needs to be done manually ...

Could you please ask your DBA to gives you the SQL requests he's run, and I'll be happy to add them in the wiki.

Best regards
Hervé

**Comment by herve91** [comment]
closing as no answer
