### ISSUE TITLE
Cannot connect to MS SQL

### ISSUE THREAD

**Issue by gevaertw** [archi-contribs/database-plugin#55]
When connecting to a MS SQL Database using Archi I get the error "Cannot connect to the database SQL exception, Please verify the database configuration in the preferences."

- The database exists and I can connect to it from that computer using a SQL Query tool, and the same credentials, I have tested the credentials, I can create a table on that DB
- The database is empty, it is a new model, the plugin should create the database.
- The database is on Azure (PAAS), however the same behaviour occurs on an on premise installed SQL server 2014 (not sure about sub version)

Plugin version 2.1.4
Archi version 4.3.0
OSX Version 10.13.6

Using the above config works perfectly when using a local installation of MySQL as Database

These are the logs:
------------

018-11-16 12:06:07 DEBUG 1091:DBGuiExportModel                         - Disabling the "Export" button.
2018-11-16 12:06:10 INFO  1179:DBGui                                    - Connecting to the database ...
2018-11-16 12:06:10 DEBUG  623:DBGui                                    - Selected database = ArchiDB_Azure (ms-sql, 85.234.217.69, 1433, ArchiDB, AzureLabAdmin, HERE WAS MY PASSWORD)
2018-11-16 12:06:10 DEBUG  101:DBDatabaseConnection                     - Opening connection to database ArchiDB_Azure: driver=ms-sql, server=85.234.217.69, port=1433, database=ArchiDB, schema=dbo, username=AzureLabAdmin
2018-11-16 12:06:10 DEBUG  137:DBDatabaseConnection                     - JDBC class = com.microsoft.sqlserver.jdbc.SQLServerDriver
2018-11-16 12:06:10 DEBUG  140:DBDatabaseConnection                     - JDBC connection string = jdbc:sqlserver://85.234.217.69:1433;databaseName=ArchiDB
2018-11-16 12:06:10 DEBUG  146:DBDatabaseConnection                     - Connecting with username = AzureLabAdmin
2018-11-16 12:06:25 DEBUG 1091:DBGuiExportModel                         - Disabling the "Export" button.
2018-11-16 12:06:25 ERROR  448:DBGui$5                                  - Cannot connect to the database.
java.sql.SQLException: Please verify the database configuration in the preferences.
	at org.archicontribs.database.connection.DBDatabaseConnection.openConnection(DBDatabaseConnection.java:157)
	at org.archicontribs.database.connection.DBDatabaseConnection.<init>(DBDatabaseConnection.java:87)
	at org.archicontribs.database.connection.DBDatabaseImportConnection.<init>(DBDatabaseImportConnection.java:79)
	at org.archicontribs.database.GUI.DBGui.databaseSelected(DBGui.java:627)
	at org.archicontribs.database.GUI.DBGui$5.widgetSelected(DBGui.java:448)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4258)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1502)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1525)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1510)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1314)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4082)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3699)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at com.archimatetool.editor.Application.start(Application.java:81)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)

**Comment by gevaertw** [comment]
never mind, for some reason it works now on azure...

Have to check on premise again...
