### ISSUE TITLE
Cannot connect to a local MySQL database: Failed to check the database

### ISSUE THREAD

**Issue by Melody8988** [archi-contribs/database-plugin#56]
Hello, 

I have a similar situation to the previous created and closed issue, except I cannot connect a local MySQL database to Archi. When checking the database I get the error:

Failed to check the database.
SQLException: Please verify the database configuration in the preferences.

I verified that the database exists, I have verified the credentials, I can access the empty dataTable. 
I have verified many times over that all other parameters are correct, (IP = 127.0.0.1, port = 3306, Driver: mysql, the database name is the same).

Plugin version 2.1.7
Archi version 4.3.1
OSX Version 10.13.6

I do not know where to turn next :/

This is the Error:

2019-01-17 10:55:24 INFO   537:DBPreferencePage                         - Logger initialised.
2019-01-17 10:55:24 TRACE  537:DBPreferencePage                         ┌    log4j.rootLogger = TRACE, stdout, file   log4j.appender.stdout = org.apache.log4j.Console
Appender
2019-01-17 10:55:24 TRACE  537:DBPreferencePage                         │    log4j.appender.stdout.Target = System.out
2019-01-17 10:55:24 TRACE  537:DBPreferencePage                         │    log4j.appender.stdout.layout = org.apache.log4j.PatternLayout
2019-01-17 10:55:24 TRACE  537:DBPreferencePage                         │    log4j.appender.stdout.layout.ConversionPattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %4L:%-40.40
C{1} %m%n
2019-01-17 10:55:24 TRACE  537:DBPreferencePage                         │    log4j.appender.file = org.apache.log4j.FileAppender
2019-01-17 10:55:24 TRACE  537:DBPreferencePage                         │    log4j.appender.file.ImmediateFlush = true
2019-01-17 10:55:24 TRACE  537:DBPreferencePage                         │    log4j.appender.file.Append = false
2019-01-17 10:55:24 TRACE  537:DBPreferencePage                         │    log4j.appender.file.Encoding = UTF-8
2019-01-17 10:55:24 TRACE  537:DBPreferencePage                         │    log4j.appender.file.File = /Users/melodysmac/DatabasePlugin.log
2019-01-17 10:55:24 TRACE  537:DBPreferencePage                         │    log4j.appender.file.layout = org.apache.log4j.PatternLayout
2019-01-17 10:55:24 TRACE  537:DBPreferencePage                         └    log4j.appender.file.layout.ConversionPattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %4L:%-40.40C{
1} %m%n
2019-01-17 10:59:03 DEBUG   89:DBPreferencePage                         - Setting preference store
2019-01-17 10:59:03 DEBUG  101:DBPreferencePage                         - Creating field editors on preference page
2019-01-17 10:59:03 DEBUG  203:DBDatabaseEntry                          - Getting databases preferences from preference store
2019-01-17 10:59:08 DEBUG  101:DBDatabaseConnection                     - Opening connection to database archi1db: driver=mysql, server=127.0.0.1, port=3306, database
=archi1, schema=, username=melody
2019-01-17 10:59:08 DEBUG  137:DBDatabaseConnection                     - JDBC class = com.mysql.jdbc.Driver
2019-01-17 10:59:08 DEBUG  140:DBDatabaseConnection                     - JDBC connection string = jdbc:mysql://127.0.0.1:3306/archi1
2019-01-17 10:59:08 DEBUG  146:DBDatabaseConnection                     - Connecting with username = melody
2019-01-17 10:59:08 ERROR 1122:DBDatabaseEntryTableEditor               - Failed to check the database.
java.sql.SQLException: Please verify the database configuration in the preferences.
        at org.archicontribs.database.connection.DBDatabaseConnection.openConnection(DBDatabaseConnection.java:157)
        at org.archicontribs.database.connection.DBDatabaseConnection.<init>(DBDatabaseConnection.java:87)
        at org.archicontribs.database.connection.DBDatabaseImportConnection.<init>(DBDatabaseImportConnection.java:79)

**Comment by herve91** [comment]
My apologies for this late answer. I did not had time to conduct time on MAC OS but it definitively works on Windows and Linux.

I'll try to check on MAC OS this week ... and come back to you ASAP ...

Meanwhile, could you please check using command line ?
> mysql -h 127.0.0.1 archi1 -u melody-p

**Comment by Melody8988** [comment]
Hi Hervé, 

I think I should also mention I was attempting with mysql version 8. 

Now I'm attempting with MariaDB:
mysql  Ver 15.1 Distrib 10.3.12-MariaDB, for osx10.13 (x86_64) using readline 5.1

I've created some authentication problems for myself attempting to uninstall and reinstall mysql so I'll get back to you when I can log in again and can check

`mysql -h 127.0.0.1 archi1 -u melody-p`

Thanks for your help!
~Melody

**Comment by Melody8988** [comment]
Now that I switched to MariaDB, and got some help from the person I work under:

I'm not sure if this is exactly the issue but it worked for me after considering that a new hashing algorithm was introduced in MySQL 4.1 for storing passwords. I followed the example here 
[](https://mariadb.com/kb/en/library/authentication-plugin-mysql_native_password/)

Essentially:
```
SET old_passwords=0;
CREATE USER username@hostname IDENTIFIED BY 'mariadb';
```

I'm not sure if more people have found this issue in newer versions of mysql on a mac, but after doing this I was finally able to check the database successfully.

**Comment by herve91** [comment]
Thanks for the info.
