### ISSUE TITLE
Maximum open cursors exceeded 

### ISSUE THREAD

**Issue by kaiserghetto** [archi-contribs/database-plugin#60]
v2.1.9

I have a model with over 5000 elements+relationships.  I keep on getting an Oracle related error: Maximum Open Cursors Exceeded.   My DBA increased the cursors over to 5000, but I still got the error.  Any way to limit this on the plugin?

**Comment by kaiserghetto** [comment]
More info.  I have three models on my local node, two small, one big. The small ones work fine, it's the big on and it fails while reading(?) the local model.  The big model doesn't exist on the Oracle DB node.

Attaching screenshot and logs

![Capture](https://user-images.githubusercontent.com/695215/56596922-6b9b2780-65bf-11e9-8de5-8e82ee73a0f9.PNG)

[DatabasePlugin.log](https://github.com/archi-contribs/database-plugin/files/3108484/DatabasePlugin.log)

**Comment by herve91** [comment]
After reviewing my code, I eventually found a method in which I create PreparedStatement and do not close it, which results in unclosed cursors.

It will be corrected in the next version.

Thanks for pointing me out this issue.

Best regards
Hervé

**Comment by herve91** [comment]
As the fix was easy to implement, I just released the version 2.1.10 that fix the PreparedStatement.

Could you please check and confirm that the error message does not appear again ?

**Comment by kaiserghetto** [comment]
2.1.9 plugin was not able to see the updated version, so I downloaded and installed the .jar file manually
I now get
> "We successfully connected to the database but the necessary tables have not been found.  Do you wish to create them?" 

Which is not true, as I have the tables already created because I already have other models from 2.1.9.  If I click Yes, I get
> "name is already used by an existing object" on both Oracle and MySQL

If I click No, I get 
> "Necessary tables not found"

Log below for Yes case (Sorry for terrible formatting)

> 2019-04-23 16:52:18 INFO   541:DBPreferencePage                         - Logger initialised.
2019-04-23 16:52:21 INFO  1188:DBGui                                    - Connecting to the database ...
2019-04-23 16:52:21 INFO  1188:DBGui                                    - Checking the database structure...
2019-04-23 16:52:31 INFO  1188:DBGui                                    - Creating necessary database tables ...
2019-04-23 16:52:31 ERROR  167:DBGuiExportModel                         - Cannot use this database.
java.sql.SQLSyntaxErrorException: ORA-00955: name is already used by an existing object

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1052)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:537)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:255)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:610)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:213)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:37)
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:887)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1136)
	at oracle.jdbc.driver.OracleStatement.executeUpdateInternal(OracleStatement.java:1678)
	at oracle.jdbc.driver.OracleStatement.executeLargeUpdate(OracleStatement.java:1643)
	at oracle.jdbc.driver.OracleStatement.executeUpdate(OracleStatement.java:1630)
	at oracle.jdbc.driver.OracleStatementWrapper.executeUpdate(OracleStatementWrapper.java:282)
	at org.archicontribs.database.connection.DBDatabaseConnection.request(DBDatabaseConnection.java:1327)
	at org.archicontribs.database.connection.DBDatabaseConnection.createTables(DBDatabaseConnection.java:336)
	at org.archicontribs.database.connection.DBDatabaseConnection.checkDatabase(DBDatabaseConnection.java:291)
	at org.archicontribs.database.GUI.DBGui.databaseSelected(DBGui.java:648)
	at org.archicontribs.database.GUI.DBGui$5.widgetSelected(DBGui.java:457)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:802)
	at org.archicontribs.database.GUI.DBGui.getDatabases(DBGui.java:581)
	at org.archicontribs.database.GUI.DBGuiExportModel.run(DBGuiExportModel.java:167)
	at org.archicontribs.database.menu.DBMenuModelExportHandler.execute(DBMenuModelExportHandler.java:47)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:390)
	at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:820)
	at org.eclipse.ui.menus.CommandContributionItem.lambda$3(CommandContributionItem.java:797)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at com.archimatetool.editor.Application.start(Application.java:82)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
Caused by: Error : 955, Position : 19, Sql = CREATE TABLE Archi.database_version (archi_plugin varchar(50) NOT NULL, version integer NOT NULL), OriginalSql = CREATE TABLE Archi.database_version (archi_plugin varchar(50) NOT NULL, version integer NOT NULL), Error Msg = ORA-00955: name is already used by an existing object

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
	... 71 more

**Comment by herve91** [comment]
Could you please provide me with your Oracle version and the Operating system on which you run Archi, I will install the same to conduct more tests ...

**Comment by kaiserghetto** [comment]
Oracle 12.1.0.2 on Linux Red Hat
Archi is on Windows 10

**Comment by herve91** [comment]
Thanks. I'm downloading version 12.1.0.2 from Oracle site. I'll let you know ASAP.

**Comment by herve91** [comment]
In fact, version 2.1.10 introduced a big issue on the SQL requests and I basically released the new version too quickly.

I just released the version 2.1.11 that works well on my 12.1.0.2. database (default number of cursors) with quite a lot of objects (around 30.000 objects).

Could you please confirm it works well on your side ?

**Comment by kaiserghetto** [comment]
Sorry for the late reply.  Just tried the new version and it works.
Thanks!

**Comment by herve91** [comment]
Thanks for your feed back.

Best regards
Hervé
