### ISSUE TITLE
After cleaning unused element, export to database failed to recalculate check sums and rolls back

### ISSUE THREAD

**Issue by xmayeur** [archi-contribs/database-plugin#82]
After cleaning unused element, export to database failed to recalculate check sums and rolls back
Not always reproducible.
Don't know what action to take to correct the issue like suggested in the message :-) 

Here the log file
```
2019-12-10 11:52:01 INFO    63:DBMenuConvertIdsHandler        - Checking IDs ...
2019-12-10 11:52:01 INFO   121:DBMenuConvertIdsHandler        - 0 IDs have been replaced.
2019-12-10 11:52:07 INFO   169:DBGuiExportModel               - Connecting to the database ...
2019-12-10 11:52:07 INFO   169:DBGuiExportModel               - Checking the database structure...
2019-12-10 11:52:07 INFO  1657:DBGuiExportModel               - Exporting model: 
2019-12-10 11:52:07 INFO  1685:DBGuiExportModel               - Calculating model's checksum.
2019-12-10 11:52:07 INFO   169:DBGuiExportModel               - Comparing the model to the database ...
2019-12-10 11:52:07 INFO   169:DBGuiExportModel               - Checking if view screenshots are required
2019-12-10 11:52:07 INFO   169:DBGuiExportModel               - Calculating number of new, updated and deleted components.
2019-12-10 11:52:07 INFO  1646:DBGuiExportModel               - The model needs to be exported to the database.
2019-12-10 11:52:07 INFO   169:DBGuiExportModel               - Checking for conflicts ...
2019-12-10 11:52:07 INFO   169:DBGuiExportModel               - Removing from the model the elements that have been deleted in the database ...
2019-12-10 11:52:07 INFO   169:DBGuiExportModel               - Importing components from the database ...
2019-12-10 11:52:07 INFO  1925:DBGuiExportModel               - There is no folder to import.
2019-12-10 11:52:07 INFO  1959:DBGuiExportModel               - Importing new elements ...
2019-12-10 11:52:07 INFO   169:DBGuiExportModel               - Importing new elements ...
2019-12-10 11:52:08 INFO  1990:DBGuiExportModel               - Importing new relationships ...
2019-12-10 11:52:08 INFO   169:DBGuiExportModel               - Importing new relationships ...
2019-12-10 11:52:08 INFO  2019:DBGuiExportModel               - There is no view to import.
2019-12-10 11:52:08 INFO  2050:DBGuiExportModel               - There is no view object to import.
2019-12-10 11:52:08 INFO  2081:DBGuiExportModel               - There is no view connection to import.
2019-12-10 11:52:08 INFO   169:DBGuiExportModel               - Checking if components have been moved to new folder ...
2019-12-10 11:52:08 INFO  2174:DBGuiExportModel               - There is no component to move to a new folder.
2019-12-10 11:52:08 INFO   169:DBGuiExportModel               - Recalculating checksums 
2019-12-10 11:52:08 INFO   169:DBGuiExportModel               - Comparing the model to the database ...
2019-12-10 11:52:08 ERROR  169:DBGuiExportModel               ┌ Failed to recalculate checksums.
2019-12-10 11:52:08 ERROR  169:DBGuiExportModel               └ null
2019-12-10 11:52:08 ERROR  169:DBGuiExportModel               ┌ Failed to recalculate checksums.
2019-12-10 11:52:08 ERROR  169:DBGuiExportModel               │ 
2019-12-10 11:52:08 ERROR  169:DBGuiExportModel               └ The transaction has been rolled back to leave the database in a coherent state. You may solve the issue and export again your components.
java.lang.NullPointerException
	at org.archicontribs.database.model.DBMetadata.getDBMetadata(DBMetadata.java:968)
	at org.archicontribs.database.connection.DBDatabaseExportConnection.getHashMapVersionFromDatabase(DBDatabaseExportConnection.java:322)
	at org.archicontribs.database.connection.DBDatabaseExportConnection.getAllVersionFromDatabase(DBDatabaseExportConnection.java:650)
	at org.archicontribs.database.GUI.DBGuiExportModel.compareModelToDatabase(DBGuiExportModel.java:1190)
	at org.archicontribs.database.GUI.DBGuiExportModel.export(DBGuiExportModel.java:2189)
	at org.archicontribs.database.GUI.DBGuiExportModel$1.widgetSelected(DBGuiExportModel.java:128)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4173)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1081)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:780)
	at org.archicontribs.database.GUI.DBGuiExportModel.connectedToDatabase(DBGuiExportModel.java:1067)
	at org.archicontribs.database.GUI.DBGui.databaseSelected(DBGui.java:714)
	at org.archicontribs.database.GUI.DBGui$5.widgetSelected(DBGui.java:471)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4173)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1081)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:780)
	at org.archicontribs.database.GUI.DBGui.getDatabases(DBGui.java:619)
	at org.archicontribs.database.GUI.DBGuiExportModel.run(DBGuiExportModel.java:169)
	at org.archicontribs.database.menu.DBMenuModelExportHandler.execute(DBMenuModelExportHandler.java:52)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:95)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:498)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:389)
	at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:783)
	at org.eclipse.ui.menus.CommandContributionItem.lambda$3(CommandContributionItem.java:760)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4173)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3986)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3585)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:633)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at com.archimatetool.editor.Application.start(Application.java:84)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)

````

**Comment by herve91** [comment]
This error is very strange as it means that an object id not referenced as part of the model. What I do not understand is how this can happens.

the model I'm using to test my plugin has got more that 9000 element, 11000 relationships, 1000 graphical objects and I do not observe the same issue than you.

I'll conduct more tests and I'll let you know.

**Comment by herve91** [comment]
Closed as failed to reproduce the issue. Please try with newer plugin and reopen if you still encounter the error message.
